version: '3.4'

services: 
  proxy:
    image: custom_nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "2500:80"
    # volumes: 
    #   - customng:/usr/share/nginx/html
    networks: 
      - custom_network

  seq:
    image: datalust/seq:latest
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - "3000:80"
    networks: 
      - custom_network

networks: 
  custom_network:

volumes: 
  customng: